FROM node:18-alpine3.17

WORKDIR /usr/src

COPY . .
# COPY ./.env.production ./.env

RUN npm install --quiet --no-optional --no-fund --loglevel=error
RUN npm run build

EXPOSE 8083

CMD [ "npm", "run", "start:prod" ]
